# .circleci/config.yaml

version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build-and-test-backend:
    executor: node-executor
    working_directory: ~/repo/backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-backend-dependencies-{{ checksum "backend/package-lock.json" }}
            - v1-backend-dependencies-
      - run:
          name: Install Backend Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-backend-dependencies-{{ checksum "backend/package-lock.json" }}
      - run:
          name: Run Backend Tests
          command: npm test

  build-and-test-frontend:
    executor: node-executor
    working_directory: ~/repo/frontend
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}
            - v1-frontend-dependencies-
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Run Frontend Tests
          command: npm test

  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_TOKEN: $SONAR_TOKEN
    steps:
      - checkout
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.organization="mikylenaidoo" \
              -Dsonar.projectKey="mikylenaidoo_APDS-POE" \
              -Dsonar.sources="backend,frontend/src" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  build-test-and-scan:
    jobs:
      - build-and-test-backend
      - build-and-test-frontend
      - sonar-scan:
          requires:
            - build-and-test-backend
            - build-and-test-frontend
